In [51]:
import torch
import torch.nn as nn
# import torch.nn.functional as Fimport torch

# 定义一个包含指定数值的张量
x= torch.tensor([[1, 2, 3, 4],
                       [5, 6, 7, 8],
                      [9, 10, 11, 12],
                       [13, 14, 15, 16]])
# x = torch.rand(1, 1, 4, 4)
print(x)
print(x.shape)

# tensor = torch.rand(1, 3, 4, 4)

# print(tensor)


tensor = torch.tensor([[[[1, 1, 1, 1],
                        [2, 2, 2, 2],
                        [3, 3, 3, 3],
                        [4, 4, 4, 4]],
                       [[1, 1, 1, 1],
                        [2, 2, 2, 2],
                        [3, 3, 3, 3],
                        [4, 4, 4, 4]]]])
print(tensor.shape)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])
torch.Size([4, 4])
torch.Size([1, 2, 4, 4])


In [98]:
    def h_transform( x):
        # h_transform 函数对输入特征进行了一个水平方向的变换（或者说扩展），然后再通过 self.deconv3 执行卷积操作。
        # h_transform 函数实际上是对输入特征在水平方向上进行了一定的操作，相当于引入了横向上的信息交互，
        shape = x.size()
        x = torch.nn.functional.pad(x, (0, shape[-1]))  # # 在特征图的右侧填充与宽度相同大小的0，实际上就是在水平方向上扩展了一倍
        x = x.reshape(shape[0], shape[1], -1)[..., :-shape[-1]]  # # 将特征图 reshape 成三维张量，最后一维是原宽度的两倍
#         x = x.reshape(shape[0], shape[1], shape[2], 2*shape[3]-1)  # 再将特征图 reshape 回原始形状，但是宽度变成了原来的两倍减一
        return x

#     deconv3 = nn.Conv2d(in_channels=2
#             out_channels=2,  kernel_size=(4, 1), padding=(4, 0))


In [99]:
x = h_transform(tensor)
print(x)
print(x.shape)
# x3=deconv3(x3)

tensor([[[1, 1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 3, 3, 3, 3, 0, 0, 0,
          0, 4, 4, 4, 4],
         [1, 1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 3, 3, 3, 3, 0, 0, 0,
          0, 4, 4, 4, 4]]])
torch.Size([1, 2, 28])


In [104]:
    def h_transform2( x):
        # h_transform 函数对输入特征进行了一个水平方向的变换（或者说扩展），然后再通过 self.deconv3 执行卷积操作。
        # h_transform 函数实际上是对输入特征在水平方向上进行了一定的操作，相当于引入了横向上的信息交互，
        shape = x.size()
        x = torch.nn.functional.pad(x, (0, shape[-1]))  # # 在特征图的右侧填充与宽度相同大小的0，实际上就是在水平方向上扩展了一倍
        x = x.reshape(shape[0], shape[1], -1)[..., :-shape[-1]]  # # 将特征图 reshape 成三维张量，最后一维是原宽度的两倍
        x = x.reshape(shape[0], shape[1], shape[2], 2*shape[3]-1)  # 再将特征图 reshape 回原始形状，但是宽度变成了原来的两倍减一
        return x

In [105]:
x = h_transform2(tensor)
print(x)
print(x.shape)

tensor([[[[1, 1, 1, 1, 0, 0, 0],
          [0, 2, 2, 2, 2, 0, 0],
          [0, 0, 3, 3, 3, 3, 0],
          [0, 0, 0, 4, 4, 4, 4]],

         [[1, 1, 1, 1, 0, 0, 0],
          [0, 2, 2, 2, 2, 0, 0],
          [0, 0, 3, 3, 3, 3, 0],
          [0, 0, 0, 4, 4, 4, 4]]]])
torch.Size([1, 2, 4, 7])


In [100]:
 def inv_h_transform( x):
        shape = x.size()
        # # 将输入特征图x按照给定的形状重新排列，其中-1表示自动计算该维度的大小，.contiguous()表示返回一个内存连续的tensor。
        x = x.reshape(shape[0], shape[1], -1).contiguous()
        # 对排列后的特征图进行填充操作，沿着最后两个维度分别在右侧和下侧填充0
        x = torch.nn.functional.pad(x, (0, shape[-2]))
        x = x.reshape(shape[0], shape[1], shape[-2], 2*shape[-2])
        # 取得到的特征图的子区域，即沿着最后一个维度取从0到shape[-2]（不包括shape[-2]）的部分
        x = x[..., 0: shape[-2]]
        return x


tensor([[[1, 1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 3, 3, 3, 3, 0, 0, 0,
          0, 4, 4, 4, 4],
         [1, 1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 3, 3, 3, 3, 0, 0, 0,
          0, 4, 4, 4, 4]]])
torch.Size([1, 2, 28])


In [78]:
x4= inv_h_transform(x3)
print(x4)


tensor([[[[1, 1, 1, 1],
          [2, 2, 2, 2],
          [3, 3, 3, 3],
          [4, 4, 4, 4]],

         [[1, 1, 1, 1],
          [2, 2, 2, 2],
          [3, 3, 3, 3],
          [4, 4, 4, 4]]]])
